package githubcontrollerstore

const schemaSQL = `
CREATE TABLE IF NOT EXISTS controller_metadata (key TEXT PRIMARY KEY, value TEXT NOT NULL) STRICT;
CREATE TABLE IF NOT EXISTS processed_deliveries (receiver_id TEXT NOT NULL, outbox_id TEXT NOT NULL, delivery_id TEXT NOT NULL, projection_kind TEXT NOT NULL, projection_digest TEXT NOT NULL, decision TEXT NOT NULL, installation_id INTEGER, base_repository_id INTEGER, pull_request_number INTEGER, generation INTEGER, target_id TEXT, job_id TEXT, processed_at TEXT NOT NULL, record_digest TEXT NOT NULL, PRIMARY KEY(receiver_id,outbox_id)) STRICT;
CREATE TABLE IF NOT EXISTS reconcile_leases (installation_id INTEGER NOT NULL, base_repository_id INTEGER NOT NULL, pull_request_number INTEGER NOT NULL, owner TEXT NOT NULL, lease_generation INTEGER NOT NULL, acquired_at TEXT NOT NULL, expires_at TEXT NOT NULL, PRIMARY KEY(installation_id,base_repository_id,pull_request_number)) STRICT;
CREATE TABLE IF NOT EXISTS pull_request_state (installation_id INTEGER NOT NULL, base_repository_id INTEGER NOT NULL, pull_request_number INTEGER NOT NULL, generation INTEGER NOT NULL, eligibility TEXT NOT NULL, current_target_id TEXT, current_job_id TEXT, base_owner TEXT, base_name TEXT, base_commit_id TEXT, head_repository_id INTEGER, head_commit_id TEXT, updated_at TEXT NOT NULL, PRIMARY KEY(installation_id,base_repository_id,pull_request_number)) STRICT;
CREATE TABLE IF NOT EXISTS targets (target_id TEXT PRIMARY KEY, target_json TEXT NOT NULL, created_at TEXT NOT NULL) STRICT;
CREATE TABLE IF NOT EXISTS jobs (job_id TEXT PRIMARY KEY, target_id TEXT NOT NULL, generation INTEGER NOT NULL, state TEXT NOT NULL, required_tiers_json TEXT NOT NULL, job_json TEXT NOT NULL, created_at TEXT NOT NULL) STRICT;
CREATE TABLE IF NOT EXISTS attempts (attempt_id TEXT PRIMARY KEY, job_id TEXT NOT NULL, target_id TEXT NOT NULL, generation INTEGER NOT NULL, attempt_number INTEGER NOT NULL, reason TEXT NOT NULL, state TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(job_id,attempt_number)) STRICT;
CREATE TABLE IF NOT EXISTS source_requests (sequence INTEGER PRIMARY KEY AUTOINCREMENT, request_id TEXT NOT NULL UNIQUE, target_id TEXT NOT NULL, job_id TEXT NOT NULL, generation INTEGER NOT NULL, installation_id INTEGER NOT NULL, pull_request_number INTEGER NOT NULL, base_repository_id INTEGER NOT NULL, base_owner TEXT NOT NULL, base_name TEXT NOT NULL, base_commit_id TEXT NOT NULL, head_repository_id INTEGER NOT NULL, head_owner TEXT NOT NULL, head_name TEXT NOT NULL, head_commit_id TEXT NOT NULL, state TEXT NOT NULL, lease_owner TEXT, lease_generation INTEGER NOT NULL DEFAULT 0, lease_expires_at TEXT, attempt_count INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, completed_at TEXT, source_store_id TEXT, source_metadata_digest TEXT, source_import_profile_version TEXT, source_object_format TEXT, source_base_tree_id TEXT, source_head_tree_id TEXT, source_limitations_json TEXT) STRICT;
CREATE INDEX IF NOT EXISTS source_requests_claim_idx ON source_requests(state,sequence);
CREATE TABLE IF NOT EXISTS check_bindings (app_id INTEGER NOT NULL, installation_id INTEGER NOT NULL, repository_id INTEGER NOT NULL, pull_request_number INTEGER NOT NULL, check_run_id INTEGER NOT NULL, external_id TEXT NOT NULL, target_id TEXT NOT NULL, job_id TEXT NOT NULL, controller_generation INTEGER NOT NULL, publication_generation INTEGER NOT NULL, PRIMARY KEY(app_id,repository_id,check_run_id)) STRICT;
`
